{% set name = "dash-renderer" %}
{% set filename = "dash_renderer" %}
{% set version = "0.16.2" %}
{% set sha256 = "469de6c7593cde8b64549c039d113c6973031c889bddfe276673aa052abe827b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - dash_renderer
    - dash_renderer.version

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-renderer
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Front-end component renderer for dash'

extra:
  recipe-maintainers:
    - moorepants
