travis:
  secure:
    BINSTAR_TOKEN: d5JjoWGFOMBYuGGEz1EreQhO29ycnEoYD0h5DLqnO8WRUCfRzwGFW+7fHWBc9RynUu8pMz5cW9ma7C08Xbq2h/vpEm8/zCnv8x/sNzC/Vut4mlf5PrlfSmmt3YuI8kzO17i0emKTwo/q0CbgxHrlVakmmiiq9prUdY7GLvc71bXiZZ8MczcGtk74iGv0kX3SdHM3CawT91Lk0WENnKKCs5BeK7KpmT7sepOJ1/3twCk9IsJPkLGVoc7S26pRO7MtUpC7KrMd2RtjnqV33wt7VNd4BT65MvlTjpFd8EKlzMziDIvMKDP/PvjtsAiMKkFuoxWoc1OOsMUkeBgxs6u1Wi/fykWRn9AZ3CsLLUkXWoWauLxQn7ZelZNX4gFbiKJWbCSdgWxZ5e01PHeFlc7Eep22tgj+kAtoZyA3iD1U/T0H1d2B52y2phWnCm+nsKY12Stj635kRe7MAew5hoCwjhw37roFRnoGYLPKBY4rlMEXJ3yieXEPqXCFiqkfl3ODT1rSSsOrMt8XSJTe5OlCmcY/FD9JNqNvLxae/SaJhpUbv+zQ4nbZ0HjyxQNqgKf08VGBJgbBQWNc/e4mgwdkochhNLITIiIdsbYs58P/4zm13WaJKHhqCTBZj6fuJDQPBV3w2QmDj9tVjKbpJFgeOHbYexyPwOcQ5LFOaK2/Bzw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
