travis:
  secure:
    BINSTAR_TOKEN: iYWqkDkyDF7S8eE4TuiDXrgNd7EQ3uJHXxCVmaBwu9kTHhQmDfT8d+qbUkqPO6VlWUouI1J72UAQRzKU4XGnN2rhqpjK3Cwf/RI1JYElTgYd9dQfjiiTYIlsZPhVZDRk8xr4QsNFEqR6qY8BmAIeDHc3/SaDhISaKGpKK0ZvaNRRdFntjNG4/9x9cvpKABJpWBQAepRaS1tAi0GF+qenNP9cex8w8qlHlDITaPNhNeSV5NaJ3KHhCet/YmJp/SJw1iX9XD2Zi/2a1g8PUfa2PECpogISWPABzOwu2J6Fp719Hq7Xc28gq4zv5Gh1yqVvD4yCrtPJXsI7GER9spfoSrDIVjKD8t4ayqNJN5mx3Zz+gK9wuX8t7tX195ciM+wVjaX1gjxWq7aGgV2G+WeuE+8ttoCNGFR1WOWFG2CQ5kVpo3O1PFmWQiQ7w8f8i2lyOTSL+ml29SvMfe0ZMO0276DnNgEISYInO3xahXJ1qKE5BYi5R09zCP+IaRMvFqrCCs2n1M98gdIH+KBHxxuSmAMm1e0A7XopCNgBZ9wssnar7s001R9vUTJrOSYK3uvuJZBMaJXbDCQ0IwtySw09rSOsNwbFIx8FhL4aDVEUfMVoghqZdS0OU3LjC6356rqhMs3pgrzvqtac0aSQOrcTYEt5a73coip64Pi72jTPBfg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
